Update async functions for more clarity
ZachAR3/PineappleEA-GUI pull request #71
Opened 2024-04-13 13:31 UTC by matmat37000

The export tag is removed for [Scripts/SettingsResource.cs](https://github.com/ZachAR3/YuzuToolbox/compare/main...matmat37000:YuzuToolbox:add-ryujinx-support#diff-8f6160445c6b271b35d5fd34eefa6dcac29d08f55b35ae8894588cbd3a649636) to avoid an error

2024-04-14 04:49 UTC, ZachAR3 commented
THe export tag is required for it to save properly using Godots function, not sure why it's giving you an error, unless its unrelated as the master branch is a bit of a disaster atm; I will try and get an updated branch out soon and you can see if that fixes it. The rest all looks good though.

2024-04-14 11:10 UTC, ZachAR3 reviewed
The name changing for clarity is fine, but many of the functions are quite different with this change, and testing will be difficult until I fully integrate the Ryujinx / mulit-source aspects. Due to this, this won't be able to be implemented for a bit, as I feel many of the async changes are likely to cause freezes in the program while events are happening, which is something I have strived to avoid. Once I am done rewriting the installer though, this can be refactored and I will properly test and implement it.

2024-04-14 11:15 UTC, matmat37000 commented
I will wait so 👍

2024-04-14 12:33 UTC, ZachAR3 commented
> I will wait so 👍

Alright, thanks for all the help! Made some good progress today, big thing I have had to redo is all of the versioning since Ryujinx uses a string while Yuzu uses an int, but the new system actually pulls proper versions from the GitHub instead of assuming the versions will be in sequential order which isn't always the case.

2024-04-14 17:03 UTC, ZachAR3 requested changes
This is a nice helper script, however, this isn't feasible for the majority of users for one key reason. The ridiculously low GithubAPI request limit (60) for unauthenticated users. I actually went through and tested the Release.GetAll functions with octokit since it's nicer than webscraping but for every version it grabs it uses a request, which means it will burn through all guest requests in 1 or 2 launches of the app. Checkout what I did for web scraping and see if you can make it manageable as a backup, otherwise most of these seem necessary since for downloading assets it's only used in the TOTK grabber, and I use the "GetAllContents" function unless this is meant to replace something else I'm missing. The version grabber is also largely unnecessary IMO, since it's 1 function that will need to exist in the installer anyway in order to parse the data.

2024-04-14 17:04 UTC, ZachAR3 commented
> I will wait so 👍

@matmat37000 I just pushed a big commit which makes the installer side of the app mostly usable, so it's now possible to merge your PR. Checkout the changes since a lot of them conflict with the PR and I also found a lot of changes unnecessary, but if you can justify them I will consider it (check my reviews / requested changes for details)

2024-04-15 05:44 UTC, matmat37000 commented
I'll watch this tomorrow @ZachAR3

2024-04-15 07:07 UTC, matmat37000 commented
@ZachAR3 do you have a Discord account ? So we can discuss more easily

2024-04-15 07:21 UTC, matmat37000 commented
> This is a nice helper script, however, this isn't feasible for the majority of users for one key reason. The ridiculously low GithubAPI request limit (60) for unauthenticated users. I actually went through and tested the Release.GetAll functions with octokit since it's nicer than webscraping but for every version it grabs it uses a request, which means it will burn through all guest requests in 1 or 2 launches of the app. Checkout what I did for web scraping and see if you can make it manageable as a backup, otherwise most of these seem necessary since for downloading assets it's only used in the TOTK grabber, and I use the "GetAllContents" function unless this is meant to replace something else I'm missing. The version grabber is also largely unnecessary IMO, since it's 1 function that will need to exist in the installer anyway in order to parse the data.

You can create a [Github token](https://github.com/settings/tokens) or [Fine-grained tokens](https://github.com/settings/tokens?type=beta) easily or ask user to create it them self to allow more API calls
![image](https://github.com/ZachAR3/YuzuToolbox/assets/68553121/1046e07b-49c9-4d48-8202-d24e6fcf6ac8)

> Sorry if I'm late, I didn't see this message yesterday (I'm UTC +02:00 btw)

2024-04-15 11:51 UTC, ZachAR3 commented
@matmat37000 5,000 requests could still easily be saturated, as the TOTK mod grabber can easily burn through hundreds or thousands. Additionally, there doesn't to be any real benefit over my web scraping approach which comes with no limit + if I wanted to expand the number of versions retrieved the GetAll command doesn't actually get all versions; it only gets 50. And having users make a Github account for an emulation app seems like a big ask, even having them provide their token is a lot with users who already have them. I can add this code as the base function and then fallback to web scraping, but what advantage does it have other than being slightly cleaner? This also doesn't address the reason for the helper script to exist at all, when a function is never repeated in my current setup.

2024-04-16 16:11 UTC, ZachAR3 commented
> @ZachAR3 do you have a Discord account ? So we can discuss more easily

@matmat37000 Sorry didn't see this until now, yeah you can add me on discord with @zachar3

2026-06-21 20:29 UTC, ZachAR3 commented
Sorry this got left here for years. Unfortunately none of it seems applicable to my rewrite of the app so I am closing it. The rewrite i'm sure has its fair share of issues if you want to take a look though. I will be more active on this project again, at the very least to keep it alive with current emulators.

2026-06-21 20:31 UTC, closed without merging